const DEFAULT_USER_ROLE = 'user';
const MODERATOR_USER_ROLE = 'moderator';
const NOTIFICATION_TIME = 2592000000;
const PRODUCTS_LIMIT = 1000;

export {
  DEFAULT_USER_ROLE,
  MODERATOR_USER_ROLE,
  NOTIFICATION_TIME,
  PRODUCTS_LIMIT,
}